services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:

