services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./dokuwiki-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

